import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, roc_auc_score

# ==============================================================================
# CONFIGURATION
# ==============================================================================
CONFIG = {
    'input_file': 'models/validation_predictions.npy',
    'output_dir': 'results'
}
# ==============================================================================

def calculate_sp_index(pd, fa):
    """
    Calculates the Sum-Product (SP) index based on the official ATLAS formula.
    pd: Probability of Detection (True Positive Rate)
    fa: False Alarm Probability (False Positive Rate)
    """
    # Using the exact mathematical definition for SP index
    return np.sqrt(np.sqrt(pd * (1 - fa)) * (pd + (1 - fa)) / 2.0)

def main():
    print("==================================================")
    print(" STARTING METRICS VALIDATION - NEURAL RINGER FPGA ")
    print("==================================================")

    os.makedirs(CONFIG['output_dir'], exist_ok=True)

    # 1. Load predictions generated by the Training Script
    if not os.path.exists(CONFIG['input_file']):
        print(f"ERROR: File {CONFIG['input_file']} not found. Run training first.")
        return

    val_predictions = np.load(CONFIG['input_file'], allow_pickle=True).item()
    
    folds_sp_max = []
    folds_auroc = []
    
    plt.figure(figsize=(12, 5))
    
    # 2. Iterate over each Fold to calculate metrics
    for fold_name, data in val_predictions.items():
        y_true = data['y_true']
        y_pred = data['y_pred']
        
        # Calculate FPR (Fa), TPR (Pd) and Thresholds using scikit-learn
        fa_array, pd_array, thresholds = roc_curve(y_true, y_pred)
        
        # Calculate AUROC (External Computer Science Metric)
        auroc = roc_auc_score(y_true, y_pred)
        folds_auroc.append(auroc)
        
        # Calculate SP Index for all thresholds
        sp_array = calculate_sp_index(pd_array, fa_array)
        
        # Find the threshold that maximizes the SP Index
        max_idx = np.argmax(sp_array)
        sp_max = sp_array[max_idx]
        best_threshold = thresholds[max_idx]
        best_pd = pd_array[max_idx]
        best_fa = fa_array[max_idx]
        
        folds_sp_max.append(sp_max)
        
        print(f"--- {fold_name.upper()} ---")
        print(f"AUROC   : {auroc:.4f}")
        print(f"SP Max  : {sp_max:.4f} (Threshold = {best_threshold:.4f})")
        print(f"P_D     : {best_pd:.4f}")
        print(f"F_A     : {best_fa:.4f}\n")

        # Plot ROC Curve for this fold
        plt.subplot(1, 2, 1)
        plt.plot(fa_array, pd_array, alpha=0.3)
        
        # Plot SP Index vs Threshold for this fold
        plt.subplot(1, 2, 2)
        plt.plot(thresholds, sp_array, alpha=0.3)

    # 3. Calculate cross-validation statistics
    print("==================================================")
    print(" FINAL CROSS-VALIDATION RESULTS (10-FOLD)         ")
    print("==================================================")
    print(f"Mean AUROC  : {np.mean(folds_auroc):.4f} ± {np.std(folds_auroc):.4f}")
    print(f"Mean SP_max : {np.mean(folds_sp_max):.4f} ± {np.std(folds_sp_max):.4f}")
    
    # 4. Finalize and save scientific plots
    plt.subplot(1, 2, 1)
    plt.title('Receiver Operating Characteristic (ROC)')
    plt.xlabel('False Alarm ($F_A$)')
    plt.ylabel('Probability of Detection ($P_D$)')
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.title('Sum-Product (SP) Index vs Threshold')
    plt.xlabel('Operation Threshold ($\tau$)')
    plt.ylabel('SP Index')
    plt.xlim(0, 1)
    plt.grid(True)

    plt.tight_layout()
    plot_path = os.path.join(CONFIG['output_dir'], 'roc_sp_curves.png')
    plt.savefig(plot_path, dpi=300)
    print(f"\n[Validation] Scientific plots saved at: {plot_path}")

if __name__ == "__main__":
    main()